//
// Generated file, do not edit! Created by nedtool 5.6 from veins/modules/messages/BatchVeri.msg.
//

#ifndef __BATCHVERI_M_H
#define __BATCHVERI_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif



struct MsgKeyPair;
class BatchVeri;
// cplusplus {{
#include "omnetpp.h"
// }}

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

/**
 * Struct generated from veins/modules/messages/BatchVeri.msg:27 by nedtool.
 */
struct VEINS_API MsgKeyPair
{
    MsgKeyPair();
    int senderId;
    int keyId;
};

// helpers for local use
void VEINS_API __doPacking(omnetpp::cCommBuffer *b, const MsgKeyPair& a);
void VEINS_API __doUnpacking(omnetpp::cCommBuffer *b, MsgKeyPair& a);

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MsgKeyPair& obj) { __doPacking(b, obj); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MsgKeyPair& obj) { __doUnpacking(b, obj); }

/**
 * Class generated from <tt>veins/modules/messages/BatchVeri.msg:32</tt> by nedtool.
 * <pre>
 * packet BatchVeri extends veins::BaseFrame1609_4
 * {
 *     int kind; // 0:info message, 1:puzzle solution, 2:from RSU include the challenge
 *     int senderId;
 *     simtime_t timestamp = 0;
 *     int beaconId;
 *     int KeyId;
 *     bool sigVrfd = false;
 *     bool PCVrfd = false;
 *     string MsgId;
 *     bool hashchainVrfd = false;
 *     bool puzzleVrfd = false;
 *     MsgKeyPair pairs[];
 * }
 * </pre>
 */
class VEINS_API BatchVeri : public ::veins::BaseFrame1609_4
{
  protected:
    int kind = 0;
    int senderId = 0;
    omnetpp::simtime_t timestamp = 0;
    int beaconId = 0;
    int KeyId = 0;
    bool sigVrfd = false;
    bool PCVrfd = false;
    omnetpp::opp_string MsgId;
    bool hashchainVrfd = false;
    bool puzzleVrfd = false;
    MsgKeyPair *pairs = nullptr;
    size_t pairs_arraysize = 0;

  private:
    void copy(const BatchVeri& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BatchVeri&);

  public:
    BatchVeri(const char *name=nullptr, short kind=0);
    BatchVeri(const BatchVeri& other);
    virtual ~BatchVeri();
    BatchVeri& operator=(const BatchVeri& other);
    virtual BatchVeri *dup() const override {return new BatchVeri(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getKind() const;
    virtual void setKind(int kind);
    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
    virtual int getBeaconId() const;
    virtual void setBeaconId(int beaconId);
    virtual int getKeyId() const;
    virtual void setKeyId(int KeyId);
    virtual bool getSigVrfd() const;
    virtual void setSigVrfd(bool sigVrfd);
    virtual bool getPCVrfd() const;
    virtual void setPCVrfd(bool PCVrfd);
    virtual const char * getMsgId() const;
    virtual void setMsgId(const char * MsgId);
    virtual bool getHashchainVrfd() const;
    virtual void setHashchainVrfd(bool hashchainVrfd);
    virtual bool getPuzzleVrfd() const;
    virtual void setPuzzleVrfd(bool puzzleVrfd);
    virtual void setPairsArraySize(size_t size);
    virtual size_t getPairsArraySize() const;
    virtual const MsgKeyPair& getPairs(size_t k) const;
    virtual MsgKeyPair& getPairsForUpdate(size_t k) { return const_cast<MsgKeyPair&>(const_cast<BatchVeri*>(this)->getPairs(k));}
    virtual void setPairs(size_t k, const MsgKeyPair& pairs);
    virtual void insertPairs(const MsgKeyPair& pairs);
    virtual void insertPairs(size_t k, const MsgKeyPair& pairs);
    virtual void erasePairs(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BatchVeri& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BatchVeri& obj) {obj.parsimUnpack(b);}

#endif // ifndef __BATCHVERI_M_H

