//
// Generated file, do not edit! Created by nedtool 5.6 from veins/modules/messages/BeaconMessage.msg.
//

#ifndef __BEACONMESSAGE_M_H
#define __BEACONMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif



class BeaconMessage;
// cplusplus {{
#include "omnetpp.h"
// }}

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

/**
 * Class generated from <tt>veins/modules/messages/BeaconMessage.msg:27</tt> by nedtool.
 * <pre>
 * packet BeaconMessage extends veins::BaseFrame1609_4
 * {
 *     int kind; // 0:info message, 1:puzzle solution, 2:from RSU include the challenge
 *     int senderId;
 *     int geosenderId;
 *     int beaconId;
 *     int KeyId;
 *     int RSUId;
 *     int geocast;
 *     string MsgId;
 *     simtime_t timestamp = 0;
 *     simtime_t timestamp_ini = 0;
 *     bool sigVrfd = false;
 *     bool puzzleVrfd = false;
 *     bool PCVrfd = false;
 *     bool hashchainVrfd = false;
 *     bool braking = false;
 *     string puzzle;
 *     veins::Coord senderPos;
 *     veins::Coord senderSpeed;
 * 
 * }
 * </pre>
 */
class VEINS_API BeaconMessage : public ::veins::BaseFrame1609_4
{
  protected:
    int kind = 0;
    int senderId = 0;
    int geosenderId = 0;
    int beaconId = 0;
    int KeyId = 0;
    int RSUId = 0;
    int geocast = 0;
    omnetpp::opp_string MsgId;
    omnetpp::simtime_t timestamp = 0;
    omnetpp::simtime_t timestamp_ini = 0;
    bool sigVrfd = false;
    bool puzzleVrfd = false;
    bool PCVrfd = false;
    bool hashchainVrfd = false;
    bool braking = false;
    omnetpp::opp_string puzzle;
    veins::Coord senderPos;
    veins::Coord senderSpeed;

  private:
    void copy(const BeaconMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BeaconMessage&);

  public:
    BeaconMessage(const char *name=nullptr, short kind=0);
    BeaconMessage(const BeaconMessage& other);
    virtual ~BeaconMessage();
    BeaconMessage& operator=(const BeaconMessage& other);
    virtual BeaconMessage *dup() const override {return new BeaconMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getKind() const;
    virtual void setKind(int kind);
    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);
    virtual int getGeosenderId() const;
    virtual void setGeosenderId(int geosenderId);
    virtual int getBeaconId() const;
    virtual void setBeaconId(int beaconId);
    virtual int getKeyId() const;
    virtual void setKeyId(int KeyId);
    virtual int getRSUId() const;
    virtual void setRSUId(int RSUId);
    virtual int getGeocast() const;
    virtual void setGeocast(int geocast);
    virtual const char * getMsgId() const;
    virtual void setMsgId(const char * MsgId);
    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);
    virtual omnetpp::simtime_t getTimestamp_ini() const;
    virtual void setTimestamp_ini(omnetpp::simtime_t timestamp_ini);
    virtual bool getSigVrfd() const;
    virtual void setSigVrfd(bool sigVrfd);
    virtual bool getPuzzleVrfd() const;
    virtual void setPuzzleVrfd(bool puzzleVrfd);
    virtual bool getPCVrfd() const;
    virtual void setPCVrfd(bool PCVrfd);
    virtual bool getHashchainVrfd() const;
    virtual void setHashchainVrfd(bool hashchainVrfd);
    virtual bool getBraking() const;
    virtual void setBraking(bool braking);
    virtual const char * getPuzzle() const;
    virtual void setPuzzle(const char * puzzle);
    virtual const veins::Coord& getSenderPos() const;
    virtual veins::Coord& getSenderPosForUpdate() { return const_cast<veins::Coord&>(const_cast<BeaconMessage*>(this)->getSenderPos());}
    virtual void setSenderPos(const veins::Coord& senderPos);
    virtual const veins::Coord& getSenderSpeed() const;
    virtual veins::Coord& getSenderSpeedForUpdate() { return const_cast<veins::Coord&>(const_cast<BeaconMessage*>(this)->getSenderSpeed());}
    virtual void setSenderSpeed(const veins::Coord& senderSpeed);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BeaconMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BeaconMessage& obj) {obj.parsimUnpack(b);}

#endif // ifndef __BEACONMESSAGE_M_H

